{% set name = "draftjs_exporter" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/draftjs_exporter-{{ version }}.tar.gz
  sha256: 2efee45d4bb4c0aaacc3e5ea2983a29a29381e02037f3f92a6b12706d7b87e1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - draftjs_exporter
    - draftjs_exporter.engines
    - draftjs_exporter.utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/springload/draftjs_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Library to convert rich text from Draft.js raw ContentState to HTML
  description: 
    Library to convert Draft.js ContentState to HTML
  doc_url: https://github.com/springload/draftjs_exporter
  dev_url: https://github.com/springload/draftjs_exporter

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
