{% set name = "draftjs_exporter" %}
{% set version = "2.1.5" %}
{% set sha256 = "8430b6c0f2a1c644ef9959b36f2f36f093f8209b94f81b4443216d3f386a3bce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  requires:
    - beautifulsoup4 >=4.4.1,<5
    - html5lib >=0.999,<=1.0b10
    - lxml >=3.6.0
    - tox >=2.3.1
    - markov_draftjs ==0.1.1
    - memory_profiler ==0.47
    - psutil ==5.4.1
    - coverage >=4.1.0
    - flake8 >=3.2.0
    - isort ==4.2.5
  imports:
    - draftjs_exporter
    - draftjs_exporter.engines
    - draftjs_exporter.utils


about:
  home: https://github.com/springload/draftjs_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Library to convert Draft.js ContentState to HTML'
  description: 
    Library to convert Draft.js ContentState to HTML
  doc_url: https://github.com/springload/draftjs_exporter
  dev_url: https://github.com/springload/draftjs_exporter

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
