{% set name = "draftjs_exporter" %}
{% set version = "3.0.0" %}
{% set sha256 = "e98d3ff0af0974c3f3640145e194e5fb0ae2aa8a9ddc403e5fd9c9c0200bc176" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  requires:
    - beautifulsoup4 >=4.4.1,<5
    - html5lib >=0.999,<=1.0b10
    - lxml >=3.6.0
    - tox >=2.3.1
    - markov_draftjs ==0.1.1
    - memory_profiler ==0.47
    - psutil ==5.4.1
    - coverage >=4.1.0
    - flake8 >=3.2.0
    - isort ==4.2.5
  imports:
    - draftjs_exporter
    - draftjs_exporter.engines
    - draftjs_exporter.utils


about:
  home: https://github.com/springload/draftjs_exporter
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Library to convert Draft.js ContentState to HTML'
  description: 
    Library to convert Draft.js ContentState to HTML
  doc_url: https://github.com/springload/draftjs_exporter
  dev_url: https://github.com/springload/draftjs_exporter

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
